"""empty message

Revision ID: c48741c9262e
Revises: 7340f3d7bb2c
Create Date: 2016-11-04 16:07:07.233297

"""

# revision identifiers, used by Alembic.
revision = 'c48741c9262e'
down_revision = '7340f3d7bb2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('title', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'page', ['title'])
    op.create_unique_constraint(None, 'tag', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_constraint(None, 'page', type_='unique')
    op.drop_column('page', 'title')
    ### end Alembic commands ###
